### ISSUE TITLE
Improve bounding sphere calculations

### ISSUE THREAD

**Issue by ThatNintendoNerd** [ScanMountGoat/geometry_tools#2]
The current implementation of bounding sphere calculation works fine for meshes that have all welded vertices, but in calculation of meshes that have unwelded vertices, duplicate vertex positions offsets the bounding sphere center, resulting in the radius to be larger than is optimal.

I am presenting a solution to this, which is simple in concept: remove duplicate vertex positions from the positions list. The following Python script performs both the current calculations and new calculations and prints the result of both. The center is usually closer to vanilla, and at times, the most optimal, which can result in a more optimal bounding sphere radius.

```python
import ssbh_data_py
import numpy as np

mesh = ssbh_data_py.mesh_data.read_mesh("model.numshb")

for o in mesh.objects:
    positions_mean_old = [0, 0, 0]
    positions_mean_new = [0, 0, 0]

    print(f'Name: {o.name}, Index: {o.sub_index}')

    # Current geometry_tools calculation
    for [x, y, z] in o.positions[0].data:
        positions_mean_old += np.array([x, y, z])
    print(f'Old: {positions_mean_old / len(o.positions[0].data)}')

    # Offered geometry_tools calculation
    for [x, y, z] in np.unique(o.positions[0].data, axis=0):
        positions_mean_new += np.array([x, y, z])
    print(f'New: {positions_mean_new / len(np.unique(o.positions[0].data, axis=0))}\n')
```
This script only generates the center of the sphere, but I'd have to bet the radius is more optimal as a result.

**Comment by ScanMountGoat** [comment]
That approach might give better results in certain circumstances. I would have to look into it more to see if it's noticeably better in the general case. Some libraries assume this operation will be fast, so I'm hesitant to add any major performance changes.

The main issue with the suggestion is the use of `np.unique`. The current naive implementation runs in O(N) time where N is the number of vertices. This means that doubling the vertex count roughly doubles the running time. Sorting can ideally be done in O(N*log2(N)) time, which doesn't scale as well for large inputs. As N gets to be very large, this implementation will perform noticeable worse. Rather than 10x slower performance when going from 100 to 1000 vertices, we could see as bad as 15x slower performance. 
| N | N log2(N) |
| --- | --- | 
| 100 | ~664 |
| 1000 | ~9966 |

There are faster ways to find unique values, but sets and dictionaries don't always perform well in practice. I would have to do some benchmarks to see how big of a difference the sorting makes in practice. This is one of those problems where no one has found a fast algorithm for finding an optimal solution. Finding an optimal solution would run extremely slowly for large models. 

I may look into implementing one of the more widely known fast approximations at some point as an additional option to compute the bounding sphere. https://en.wikipedia.org/wiki/Bounding_sphere#Algorithms

**Comment by ThatNintendoNerd** [comment]
My Python implementations were just a proof of concept which, if I provided comparisons, would demonstrate the differences and greater accuracies. I suppose if one is to offer a solution in a scenario like this, then they'd need to provide comparisons or benchmarks to prove their solution is effective. I will try to do that at a later time. How you decide to implement the solution, if you decide to, is entirely up to you.

If you're favoring speed over accuracy, I would understand that. I just thought I'd point out a flaw with the current implementation in a specific case with some models. Though the option to calculate quickly or having a more precise bounding sphere would be a welcome option.

**Comment by ScanMountGoat** [comment]
You'll need to be careful to clearly define "accurate" in this case. For matching the output of an existing program, it's likely the original authors are using an existing published algorithm. When comparing to the optimal solution, we usually mean the smallest sphere that encloses all the given points. Giving a formal proof for either of these cases would be very difficult. There are probably some Python implementations of common algorithms like Ritter's algorithm floating around the internet that may give closer results to what you were observing.

In the case of using bounding volumes for depth sorting objects, it's often not critical to compute the smallest possible bounding volume as long as the comparison between spheres produces the expected results. Sometimes a larger than optimal solution is good enough, but it depends on the context of course.
